name: Publish Ardalis.Result to Nuget.org

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '7.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Ardalis.Result to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.0
      with:
        PROJECT_FILE_PATH: src/Ardalis.Result/Ardalis.Result.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
